import { describe, expect, it } from "vite-plus/test";
import { parsePulleySheets, parseStakeholderSheets } from "@capy/equity/import";
import { exportCapTableWorkbook } from "../lib/export-workbook";
import { readPulleyWorkbook } from "../lib/import-workbook";
import type { ImportSheet } from "@capy/equity/import";
import { totals } from "@capy/equity";

function fixture(): ImportSheet[] {
  return [
    {
      name: "Summary",
      rows: [
        ["Example Summary Capitalization Table"],
        ["Generated by Example, data to 09-15-2026"],
        [],
        [
          null,
          null,
          null,
          null,
          null,
          "Authorized",
          "Issued and Outstanding",
          null,
          null,
          "Capital Contribution",
        ],
        ["Stock"],
        [null, null, "Common", null, null, 1000, 400, null, null, 40],
        ["Employee Plan"],
        [null, "Plan Size", null, null, null, 200],
        [null, "Shares Available", null, null, null, null, 150],
      ],
    },
    {
      name: "Ownership",
      rows: [
        ["Example"],
        [],
        ["Stakeholder", "Stakeholder Type"],
        ["Founder", "Founder"],
        ["Employee Plan Available", ""],
      ],
    },
    {
      name: "CS-Common",
      rows: [
        ["CS-Common"],
        [],
        [
          "Certificate ID",
          "Stakeholder Name",
          "Shares Issued",
          "Shares Outstanding",
          "Price Per Share",
          "Capital Contribution",
        ],
        ["CS-1", "Founder", 300, 300, 0.1, 30],
        ["CS-1", "Employee", 100, 100, 0.1, 10],
        ["CS-3", "Former holder", 200, 0, 0.1, 20],
        ["Total", null, null, null, null, null],
      ],
    },
    {
      name: "A truncated plan name",
      rows: [
        ["Employee Plan"],
        [],
        [
          "Certificate ID",
          "Stakeholder Name",
          "Granted",
          "Outstanding",
          "Grant Type",
          "Share Class Name",
          "Equity Plan",
          "Vested Outstanding",
        ],
        ["OPT-1", "Employee", 100, 50, "ISO", "Common", "Employee Plan", 25],
      ],
    },
    {
      name: "Convertibles",
      rows: [
        ["Convertibles"],
        [],
        [
          "Convertible ID",
          "Stakeholder",
          "Principal Issued",
          "Principal Outstanding",
          "Conversion Type",
        ],
        ["SAFE-1", "Investor", 500000, 500000, "Post-Money"],
      ],
    },
  ];
}
describe("Pulley detailed export", () => {
  it("strips the summary title with mixed case and repeated whitespace", () => {
    const sheets = fixture();
    sheets[0]!.rows[0]![0] = "  Example \t  sUmMaRy Capitalization Table  ";
    expect(parsePulleySheets(sheets).name).toBe("Example");
  });
  it("rejects an oversized nonmatching title without repeated whitespace backtracking", () => {
    const sheets = fixture();
    sheets[0]!.rows[0]![0] = `Example${" ".repeat(64_000)}Unrelated title`;
    expect(() => parsePulleySheets(sheets)).toThrow();
  });
  it("stops unmatched restricted stock before it can silently change ownership", () => {
    const sheets = fixture();
    sheets[3]!.rows[3]![4] = "RSA";
    expect(() => parsePulleySheets(sheets)).toThrow("restricted-stock mapping");
  });
  it("round-trips Excel balances, custom SAFE IDs, warrants and contact fields", async () => {
    const data = parsePulleySheets(fixture());
    data.securities.find((s) => s.kind === "safe")!.certificate = "Investment-2026";
    data.securities.find((s) => s.kind === "option")!.kind = "warrant";
    data.stakeholders[0]!.email = "founder@example.com";
    data.stakeholders[0]!.fields = { Address: "1 Main Street" };
    const buffer = await exportCapTableWorkbook(data);
    const imported = await readPulleyWorkbook(buffer as ArrayBuffer, "capy.xlsx");
    expect(totals(imported)).toEqual(totals(data));
    expect(imported.securities.map((s) => s.kind)).toEqual(data.securities.map((s) => s.kind));
    expect(imported.stakeholders[0]).toMatchObject({
      email: "founder@example.com",
      fields: { Address: "1 Main Street" },
    });
  });
  it("imports supplemental contacts without SSNs", () => {
    const contacts = parseStakeholderSheets([
      {
        name: "Stakeholders",
        rows: [
          ["Name", "Email", "SSN", "Address"],
          ["Example", "person@example.com", "000-00-0000", "1 Main Street"],
        ],
      },
    ]);
    expect(contacts[0]?.fields).toEqual({
      Name: "Example",
      Email: "person@example.com",
      Address: "1 Main Street",
    });
  });
  it("recomputes FD from underlying outstanding records and reserves, excluding SAFEs and historical stock", () => {
    const data = parsePulleySheets(fixture());
    expect(totals(data)).toMatchObject({
      fullyDiluted: "600",
      outstandingStock: "400",
      outstandingAwards: "50",
      available: "150",
      capital: "500040",
      stakeholdersWithSecurities: 3,
    });
    expect(data.securities).toHaveLength(5);
    expect(data.stakeholders).toHaveLength(4);
    expect(data.plans[0]?.name).toBe("Employee Plan");
  });
  it("preserves duplicate certificate labels as distinct records", () => {
    const data = parsePulleySheets(fixture());
    const dupes = data.securities.filter((s) => s.certificate === "CS-1");
    expect(dupes).toHaveLength(2);
    expect(dupes[0]?.key).not.toBe(dupes[1]?.key);
    expect(data.warnings.some((w) => w.includes("Duplicate"))).toBe(true);
  });
  it("accepts moved header rows and reordered columns", () => {
    const sheets = fixture();
    const shares = sheets[2]!;
    shares.rows = shares.rows.map((r) => [...r].reverse());
    shares.rows.unshift([], []);
    shares.rows[2] = ["CS-Common"];
    const data = parsePulleySheets(sheets);
    expect(totals(data).outstandingStock).toBe("400");
  });
  it("rejects a summary mismatch instead of importing incomplete equity", () => {
    const sheets = fixture();
    sheets[2]!.rows[3]![3] = 299;
    expect(() => parsePulleySheets(sheets)).toThrow("summary reports 400");
  });
  it("rejects absent outstanding quantities rather than silently using zero", () => {
    const sheets = fixture();
    sheets[2]!.rows[3]![3] = null;
    expect(() => parsePulleySheets(sheets)).toThrow("required value is missing");
  });
  it("retains decimal precision", () => {
    const sheets = fixture();
    sheets[0]!.rows[5]![9] = "40.000000001";
    expect(totals(parsePulleySheets(sheets)).capital).toBe("500040.000000001");
  });
  it("rejects invalid and negative amounts", () => {
    for (const value of ["oops", -1, "NaN"]) {
      const sheets = fixture();
      sheets[2]!.rows[3]![3] = value;
      expect(() => parsePulleySheets(sheets)).toThrow("nonnegative number");
    }
  });
  it("makes unrecognized content visible", () => {
    const sheets = fixture();
    sheets.push({ name: "Unknown Securities", rows: [["Private units"], [100]] });
    expect(parsePulleySheets(sheets).warnings.some((w) => w.includes("Unknown Securities"))).toBe(
      true,
    );
  });
  it("rejects summary-only files", () => {
    expect(() => parsePulleySheets(fixture().slice(0, 2))).toThrow("No detailed securities");
  });
});
