import type { EquityImport, Security } from "@capy/equity";
import { sum } from "@capy/equity";

export async function exportCapTableWorkbook(data: EquityImport) {
  const { default: ExcelJS } = await import("exceljs");
  const book = new ExcelJS.Workbook();
  book.creator = "Capy";
  book.created = new Date();
  const suffix = data.asOf.split("-");
  const metadata = `Generated by Capy, data to ${suffix[1]}-${suffix[2]}-${suffix[0]}`;
  const summary = book.addWorksheet("Summary");
  summary.addRows([
    [`${data.name} Summary Capitalization Table`],
    [metadata],
    [],
    [
      null,
      null,
      null,
      null,
      null,
      "Authorized",
      "Issued and Outstanding",
      null,
      null,
      "Capital Contribution",
      "Par Value",
      "Price per Share",
    ],
    ["Stock"],
  ]);
  for (const c of data.classes)
    summary.addRow([
      null,
      null,
      c.name,
      null,
      null,
      c.authorized,
      sum(
        data.securities
          .filter((s) => s.kind === "share" && s.className === c.name)
          .map((s) => s.outstanding),
      ),
      null,
      null,
      c.capital,
      c.parValue,
      c.pricePerShare,
    ]);
  for (const p of data.plans)
    summary.addRows([
      [p.name],
      [null, "Plan Size", null, null, null, p.authorized],
      [null, "Shares Available", null, null, null, null, p.available],
      [null, "Plan Status", p.status || "Outstanding"],
      [null, "Board Approval", p.boardApproval || ""],
      [null, "Term Years", p.termYears ?? null],
      [null, "Plan Share Class", p.className],
    ]);
  const ownership = book.addWorksheet("Ownership");
  ownership.addRows([
    [data.name],
    [metadata],
    [],
    ["Stakeholder", "Stakeholder Type", "Stakeholder External ID"],
    ...data.stakeholders.map((p) => [p.name, p.relationship, p.externalId]),
  ]);
  const person = (s: Security) =>
    data.stakeholders.find((p) => p.key === s.stakeholderKey)?.name || "Unknown";
  const sheetNames = new Set(["Summary", "Ownership"]);
  function table(title: string, rows: Record<string, string | null>[]) {
    if (!rows.length) return;
    let name = title.slice(0, 30).replace(/[\\/*?:[\]]/g, "-");
    let n = 1;
    while (sheetNames.has(name)) name = title.slice(0, 26) + ` (${n++})`;
    sheetNames.add(name);
    const sheet = book.addWorksheet(name);
    const headers = [...new Set(rows.flatMap((r) => Object.keys(r)))];
    sheet.addRows([
      [title],
      [metadata],
      [],
      headers,
      ...rows.map((r) => headers.map((h) => r[h] ?? null)),
    ]);
    sheet.views = [{ state: "frozen", ySplit: 4 }];
    sheet.autoFilter = { from: { row: 4, column: 1 }, to: { row: 4, column: headers.length } };
    sheet.columns.forEach((col, i) => {
      col.width = i < 2 ? 28 : 20;
    });
    sheet.getRow(4).font = { bold: true, color: { argb: "FFFFFFFF" } };
    sheet.getRow(4).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF376751" } };
  }
  for (const c of data.classes) {
    const securities = data.securities.filter((s) => s.kind === "share" && s.className === c.name);
    table(
      `${c.kind === "Preferred" ? "PS" : "CS"}-${c.name}`,
      securities.map((s) => ({
        ...s.fields,
        "Certificate ID": s.certificate,
        "Stakeholder Name": person(s),
        "Issue Date": s.issuedOn,
        "Balance As Of": s.balanceAsOf || data.asOf,
        "Shares Issued": s.issued,
        "Shares Outstanding": s.outstanding,
        "Price Per Share": s.price,
        "Capital Contribution": s.capital,
        "Shares Vested": s.vested,
        "Vesting Start Date": s.vestingStart,
        "Vesting Schedule": s.vestingSchedule,
        "Equity Plan Name": s.planName,
      })),
    );
  }
  const awards = data.securities.filter((s) => !["share", "safe", "note"].includes(s.kind));
  for (const plan of new Set(awards.map((s) => s.planName)))
    table(
      plan || "Equity Awards Outside of a Plan",
      awards
        .filter((s) => s.planName === plan)
        .map((s) => ({
          ...s.fields,
          "Certificate ID": s.certificate,
          "Stakeholder Name": person(s),
          "Grant Date": s.issuedOn,
          "Balance As Of": s.balanceAsOf || data.asOf,
          Granted: s.issued,
          Outstanding: s.outstanding,
          "Grant Type":
            s.kind === "option" ? s.fields["Grant Type"] || "NSO" : s.kind.toUpperCase(),
          "Exercise Price": s.price,
          "Vested Outstanding": s.vested,
          "Equity Plan": s.planName,
          "Share Class Name": s.className,
          "Vesting Start Date": s.vestingStart,
          "Vesting Schedule": s.vestingSchedule,
        })),
    );
  table(
    "Convertibles",
    data.securities
      .filter((s) => s.kind === "safe" || s.kind === "note")
      .map((s) => ({
        ...s.fields,
        "Convertible ID": s.certificate,
        "Security Type": s.kind,
        Stakeholder: person(s),
        "Grant Date": s.issuedOn,
        "Balance As Of": s.balanceAsOf || data.asOf,
        "Principal Issued": s.issued,
        "Principal Outstanding": s.outstanding,
        Status: s.status,
      })),
  );
  // Dated vesting events, so custom schedules survive an export and re-import.
  table(
    "Vesting Events",
    data.securities
      .filter((s) => s.kind !== "rsa" && s.vestEvents?.length)
      .flatMap((s) =>
        s.vestEvents!.map((e) => ({
          "Certificate ID": s.certificate,
          "Share Class": s.className,
          "Stakeholder Name": person(s),
          "Vest Date": e.date,
          "Shares Vesting": e.shares,
        })),
      ),
  );
  table(
    "Stakeholders",
    data.stakeholders.map((p) => ({
      ...p.fields,
      Name: p.name,
      Email: p.email,
      Relationship: p.relationship,
      Type: p.entityType,
      "External ID": p.externalId,
    })),
  );
  return await book.xlsx.writeBuffer();
}
export async function downloadCapTable(data: EquityImport) {
  const buffer = await exportCapTableWorkbook(data);
  const url = URL.createObjectURL(
    new Blob([buffer as BlobPart], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    }),
  );
  const a = document.createElement("a");
  a.href = url;
  a.download = `${data.name}-cap-table-${data.asOf}.xlsx`;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
